// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3DOZuESJkTvRCJA-bcfT8QnoMwG5pn_k',
    appId: '1:508194876863:web:8fe747255da2d77d4c850a',
    messagingSenderId: '508194876863',
    projectId: 'edunova-fa954',
    authDomain: 'edunova-fa954.firebaseapp.com',
    storageBucket: 'edunova-fa954.appspot.com',
    measurementId: 'G-TTVWPRMY77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxQDtj0-cr802OQ2_t0AZ9XxZ3dVKqtCE',
    appId: '1:508194876863:android:e0350ad5321da0de4c850a',
    messagingSenderId: '508194876863',
    projectId: 'edunova-fa954',
    storageBucket: 'edunova-fa954.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIs6012MA0QxKVX2nC11W2fI4fKJHKySc',
    appId: '1:508194876863:ios:3ffd282b46e102fc4c850a',
    messagingSenderId: '508194876863',
    projectId: 'edunova-fa954',
    storageBucket: 'edunova-fa954.appspot.com',
    androidClientId: '508194876863-juc4ft9hqreh6esebil8e710ffgnnqo2.apps.googleusercontent.com',
    iosClientId: '508194876863-s5lhhfnfc8674cdducfj22gu4v63ltop.apps.googleusercontent.com',
    iosBundleId: 'com.example.bvecBees',
  );

}